#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "onedark"
    background = "dark"
    # Custom options from this point
    default_indent = 4
    enable_ale = true
    enable_googlesuggest = true
    realtime_leader_guide = true
    relativenumber = false
    # Custom config as vim functions
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    plugin_bundle_dir = "~/.local/var/cache/vimfiles/"



# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_shell = 'VimShell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'debug'

[[layers]]
name = 'fzf'

[[layers]]
name = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'lang#c'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#haskell'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#latex'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'sudo'

[[layers]]
name = 'tags'

[[layers]]
name = 'tools'

[[layers]]
name = 'tmux'

# Custom plugins
[[custom_plugins]]
name = 'tomlion/vim-solidity'

[[custom_plugins]]
name = 'ledger/vim-ledger'

[[custom_plugins]]
name = 'meatballs/vim-xonsh'
